language: node_js
node_js:
  - 10.16.0
script:
  - cd serverless/mydata
  - npm test
notifications:
  slack:
    secure: Keff3SyBZkZJ4CN063V9256q9666ldwyeNozQ1wsQPN5uN/VktvQkJr4lEg9ibp/Zj4kug7vHYSQmylgQTCPUiOD3l0NizxTrySy5f925tPIvk/7jDutzO3jeQoU0peY+nfJEsPaurZNDZDsMf8VwptVPfqMoe1HRXRVy2uP9jAAZ3ioyOWlRO/0XMNcJEFs1MXhxarx/EgcQ03CEhhcFhmj/OlWuRdRR9hCsmBA6r9FlHGnehYEZE4MPMQ2mnZDgVIZKlwwrG+73vzxERn0RBYq4cATrf8gug22X7JV24sXwV30MCocqP1UZGPgoZ2M3StE7HhNLTouGG10SZLoodJ5fLTn2zjfweRq8VJZaGh+XAYncIctKerD3ivNt5uIXIyz4GipEJH4MAsXQNhq5AxUkyN8LmwVm1gN3u4YkWMeAFZdOOKO0VOjlqMVraEXeJB9ejug4h+mBcdv07i3UWf4hKKxFvqFQCSTjNrjATiaSP4k2+koIEyw938DRBpBc6zrZawGKgBL6wWvJ6fXz0PAOHf2pWwcv43B1PDz7XrK/liKW5ev6U8JCv/80ebIBFOPyMY7FrMpxj66HhQBAxsH849ZlWlrq6UAZcVIp8ho74xk0a6QPtEN6do+WOYFzeyZ1JLoLAwh5eYu9+26WqTEAS+4wmaw3SAHO4Oj8bI=
